/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class adsbrecorder_jni_Dump1090Native */

#ifndef _Included_adsbrecorder_jni_Dump1090Native
#define _Included_adsbrecorder_jni_Dump1090Native

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     adsbrecorder_jni_Dump1090Native
 * Method:    startMonitor
 * Signature: (Ladsbrecorder/jni/NewAircraftCallback;)V
 */
JNIEXPORT void JNICALL Java_adsbrecorder_jni_Dump1090Native_startMonitor
  (JNIEnv* env, jobject thiz, jint index, jobject callback);

/*
 * Class:     adsbrecorder_jni_Dump1090Native
 * Method:    stopMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_adsbrecorder_jni_Dump1090Native_stopMonitor
  (JNIEnv* env0, jobject thiz);

/*
 * Class:     adsbrecorder_jni_Dump1090Native
 * Method:    listAllReceivers
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_adsbrecorder_jni_Dump1090Native_listAllReceivers
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
